### ISSUE TITLE
Now 2.0 not working with pug?

### ISSUE THREAD

**Issue by jbandi** [vercel/vercel#1790]
I have a simple express app using pug:
`app.set('view engine', 'pug');`

The app is working locally and was working with Now 1.0.

But it seems not to work with Now 2.0 ... for routes that are rendered with pug I get a `Internal Server Error` and in the logs: 

```
Error: Cannot find module 'pug'
    at webpackEmptyContext (/var/task/user/index.js:18675:9)
    at new View (/var/task/user/index.js:18564:38)
    ...
```

Is this a general restriction of Now 2.0?

**Comment by paulogdm** [comment]
Hello! Could you share a minimal example with us?

**Comment by jbandi** [comment]
I have created a simple reproduction here:

https://github.com/jbandi/now-pug

**Comment by paulogdm** [comment]
Thank you very much!
The code is failing in `@now/node-server` in both stable and canary branches.
When running locally `ncc run index.js` or even `ncc build index.js && cd dist && node index.js` it runs fine.

**Comment by paulogdm** [comment]
We should move this to [@zeit/now-builders](https://github.com/zeit/now-builders)!

**Comment by jbandi** [comment]
I can reproduce the problem when running the app locally with `ncc run index.js`: I get exactly the error `Error: Cannot find module 'pug'` ...

I did update the reproduction accordingly:
https://github.com/jbandi/now-pug

Running `npm start` does now reproduce the bug locally ...

**Comment by Siilwyn** [comment]
Duplicate of https://github.com/zeit/now-cli/issues/1716

**Comment by juliangruber** [comment]
> Duplicate of #1716

Closing as duplicate, please follow the above mentioned issue.
