### ISSUE TITLE
vercel dev assumes all JS are typescript

### ISSUE THREAD

**Issue by SheetJSDev** [vercel/vercel#4966]
Repro: https://github.com/sheetjs/sheetaki (live on https://sheetaki.now.sh/ so it's not a vercel production issue)

Error:

```
/usr/local/lib/node_modules/vercel/node_modules/ts-node/src/index.ts:423
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS6046: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018', 'esnext'.
```

To elicit the error, do a fresh clone of the repo, npm install, run `vercel dev` and hit the `/api/data` endpoint.

The project itself has one API endpoint that is pure JS (no typescript), but `vercel dev` treats the project as TS.

**Comment by TooTallNate** [comment]
Hi there @SheetJSDev. Thank you for the report. However, I can't seem to reproduce. Your project works as expected for me with `vc dev`.

Could you provide some more details about your setup?

* Version of Vercel CLI being used
* Version of Node.js installed
* Full logs of `vc dev --debug`

**Comment by SheetJSDev** [comment]
To be sure, the static index.html doesn't elicit the problem.  Try clicking a body link.

```
$ vercel --version
Vercel CLI 19.2.0
19.2.0
$ node --version
v14.6.0
```

The log:

```
...
> [debug] [2020-08-04T18:32:09.435Z] GET https://api.vercel.com/v1/frameworks 
> [debug] [2020-08-04T18:32:09.443Z] Spinner invoked (Retrieving project…) with a 1000ms delay
> [debug] [2020-08-04T18:32:09.444Z] GET https://api.vercel.com/www/user 
> [debug] [2020-08-04T18:32:09.445Z] GET https://api.vercel.com/projects/QmddauvNzzUy84uRVsP8FDYHAsVT5KpCScffaq5TeftGUa? 
> [debug] [2020-08-04T18:32:09.847Z] GET https://api.vercel.com/projects/QmddauvNzzUy84uRVsP8FDYHAsVT5KpCScffaq5TeftGUa? : 401.817ms
> [debug] [2020-08-04T18:32:09.851Z] GET https://api.vercel.com/www/user : 406.698ms
> [debug] [2020-08-04T18:32:09.852Z] Spinner ended (Retrieving project…)
> [debug] [2020-08-04T18:32:09.863Z] GET https://api.vercel.com/v1/frameworks : 427.415ms
> [debug] [2020-08-04T18:32:09.870Z] Fetching Environment Variables of project QmddauvNzzUy84uRVsP8FDYHAsVT5KpCScffaq5TeftGUa and target development
> [debug] [2020-08-04T18:32:09.872Z] GET https://api.vercel.com/v4/projects/QmddauvNzzUy84uRVsP8FDYHAsVT5KpCScffaq5TeftGUa/env?target=development 
> [debug] [2020-08-04T18:32:10.238Z] GET https://api.vercel.com/v4/projects/QmddauvNzzUy84uRVsP8FDYHAsVT5KpCScffaq5TeftGUa/env?target=development : 365.931ms
> [debug] [2020-08-04T18:32:10.245Z] Reading `package.json` file
> [debug] [2020-08-04T18:32:10.246Z] Reading `now.json` file
> [debug] [2020-08-04T18:32:10.250Z] Locating files /tmp/sheetaki
... (a bunch of "Ignoring" lines) ...
> [debug] [2020-08-04T18:32:10.285Z] No Runtimes need to be installed
> [debug] [2020-08-04T18:32:10.286Z] Requiring runtime: "@vercel/node"
> [debug] [2020-08-04T18:32:10.398Z] Requiring runtime: "@vercel/static-build"
> [debug] [2020-08-04T18:32:10.416Z] Adding build match for "api/data/index" with "@vercel/node@latest"
> [debug] [2020-08-04T18:32:10.416Z] Adding build match for "package.json" with "@vercel/static-build@latest"
> Creating initial build
> Building @vercel/static-build@latest:package.json
> [debug] [2020-08-04T18:32:10.418Z] Using `@vercel/static-build@0.17.6`
> [debug] [2020-08-04T18:32:10.418Z] Creating build process for "package.json"
Running "yarn run build"
... (yarn stuff) ...
> Built @vercel/static-build@latest:package.json [304ms]
> Success! Build completed
> Ready! Available at http://localhost:3000
> [debug] [2020-08-04T18:32:40.423Z] No builders were updated
```

So going to http://localhost:3000 works (it's a static HTML page).  The first link for http://localhost:3000/api/data?url=https://obamawhitehouse.archives.gov/sites/default/files/omb/budget/fy2014/assets/receipts.xls triggers the error:

```
> [debug] [2020-08-04T18:34:22.888Z] GET /api/data?url=https://obamawhitehouse.archives.gov/sites/default/files/omb/budget/fy2014/assets/receipts.xls
> [debug] [2020-08-04T18:34:22.888Z] Reading `package.json` file
> [debug] [2020-08-04T18:34:22.889Z] Reading `now.json` file
> [debug] [2020-08-04T18:34:22.890Z] Locating files /tmp/sheetaki
... (a bunch of "Ignoring" lines) ...
> [debug] [2020-08-04T18:34:22.896Z] Locating files /tmp/sheetaki: 5.764ms

/usr/local/lib/node_modules/vercel/node_modules/ts-node/src/index.ts:423
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS6046: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018', 'esnext'.
```

**Comment by TooTallNate** [comment]
I still can't reproduce with the same version of Node and Vercel CLI.

But it seems as if you have another (older) version of TypeScript installed in the require path. Note how "es2019" and "es2020" are missing from your error message, compared to on my machine:

```
$ tsc --target es2 api/data/index.js
error TS6046: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'esnext'.
```

Can you try running `node -p "require.resolve('typescript')"` and let me know if that outputs a path?

**Comment by SheetJSDev** [comment]
in the global scope at the top level, `typescript@3.2.2` is installed

upgrading to the latest version of typescript (3.9.7) resolves the issue.  Bijecting, it doesn't work on 3.4.5 (latest 3.4) but does work on 3.5.1.

Since the typescript version is discoverable using `require('typescript').version` would it make sense to add a TS semver check within vercel?

**Comment by TooTallNate** [comment]
Ok thanks for clarifying. For now, just be sure to use a recent version of TypeScript at that top-level (or just don't have it installed, as `@vercel/node` bundles a version of TypeScript that is known to be working.

We will update the behavior to only use the user's version of `typescript` if it's within the project's `node_modules` (so it will ignore the top-level copy, and instead use the version included with `@vercel/node`) which will more closely resemble the behavior in production.

**Comment by TooTallNate** [comment]
As for the original issue title, `@vercel/node` runs all code (JS and TS) through `ts-node` for dev. For JS files, this is necessary to support ES6 `import`/`export` syntax. So it is expected that dev "assumes all JS are typescript" - but your underlying issue of having an old version of `typescript` in the require path will be addressed separately.

**Comment by TooTallNate** [comment]
This is fixed as of `vercel@20.1.2-canary.1`.
