### PR TITLE
[cli] Fix vc secret rm

### PR DESCRIPTION
**Pull request by styfle**
Fixes a regression from the the refactor in https://github.com/vercel/vercel/pull/8039 that was causing the following error:

```
Error! client.prompt is not a function
```

### CODE REVIEW

**Review by cb1kenobi — APPROVED** [review]
Verified and approved

**Review by MatthewStanciu — APPROVED** [review]

**Review by TooTallNate — APPROVED** [review]
