### ISSUE TITLE
Can't deploy after bumping node version to 10.x

### ISSUE THREAD

**Issue by etomsen** [vercel/vercel#3471]
Hey, have an issue after bumping node version fro 8.10.x to 10.x (same for 12.x).
I have a sapper application build (no export as I need authentication routes), which should be served as in package.json `"start": "node __sapper__/build",`. 
However, returns `ERROR	Server is not listening Error: Cannot find module '__sapper__/build/server/server.js'` in build logs
If I check files, `__sapper__/build/server/server.js` is there. Doing `cd $INIT_CWD && node __sapper__/build` also did not help.
Turning back to node 8.10.x fixes the problem without any additional changes

node: v12.14.0
now: 16.7.0

[now.log](https://github.com/zeit/now/files/3999166/now.log)

[now-json.txt](https://github.com/zeit/now/files/3999168/now-json.txt)

thnx!

**Comment by thebspin** [comment]
I have the same issue, i was not sure what it was untill i came along this issue. node 12.x or 10.x wont work for me but 8.x does (also using sapper demo from here: https://github.com/beyonk-adventures/now-sapper-demo)

**Comment by styfle** [comment]
Hello,

This is a problem with `now-sapper`.

Please create an issue in the [now-sapper](https://github.com/thgh/now-sapper) repository.
