### PR TITLE
Use pip --upgrade when installing python function dependencies

### PR DESCRIPTION
**Pull request by coolreader18**
Passes `--upgrade` to `pip install -r` so that werkzeug 2.0 can be installed if that's a dependency of the function.

### Related Issues

> Related to https://github.com/vercel/vercel/pull/6272#issuecomment-913226139

#### Tests

I don't think there's a good way to test this, but let me know if I'm wrong - it seems like the fixture tests just check that the runtime can build them.

#### Code Review

- [x] This PR has a concise title and thorough description useful to a reviewer

### CODE REVIEW

**Comment by coolreader18** [comment]
Oh, also - as far as I can tell, `vc_init.py` works fine with werkzeug 2.0; none of the breaking changes affect what it's using.

**Review by styfle — COMMENTED** [review]
Thanks!

Please add a test fixture so we can ensure this works with Flask 2.

Take a look at this one for an example:
https://github.com/vercel/vercel/tree/cfae7ec3c291d1802fb6eec6642a0ebf792fb71d/packages/python/test/fixtures/00-request-path

Then you can run the integration tests with:

```
yarn install
yarn build
cd ./packages/python
export VERCEL_TOKEN='YourTokenHere'
yarn test-integration-once
```

Note this will make real deployments so feel free to create a test account for running these.

**Comment by coolreader18** [comment]
Added! I wasn't able to get tests working locally; every one errored with `Cannot find module '/vercel/35fd446a/.build-utils/.builder/node_modules/@vercel/python/dist/index.js'` (which was happening before as well), but hopefully it should just work in CI?

**Comment by styfle** [comment]
You probably need to run `yarn build` at the root of the repo so all packages are built at least once

I'll try running CI here: #6688

**Review by styfle — APPROVED** [review]
Great work, thanks! 🎉

**Comment by styfle** [comment]
You can try this out on canary with `FORCE_RUNTIME_TAG=canary` env var for zero config or `@vercel/python@canary` if you're using the legacy `builds` property.
