### PR TITLE
fix: Vercel Python function with ASGI for Python version >= 3.10 (specifically 3.12)

### LINKED ISSUE #11545: Python runtime does not work on Python 3.12 with ASGI
Although Python 3.12 is listed as supported by Vercel, it does not work properly with asynchronous functions.

I am trying to deploy a Starlette app (which is ASGI). Just listing Starlette as dependency did not work, as Vercel complained that it's missing `aiohttp`:

```
LAMBDA_WARNING: Unhandled exception. [...]
[ERROR] Runtime.ImportModuleError: Unable to import module 'vc__handler__python': No module named 'aiohttp'
Traceback (most recent call last):
```

So, I've added it to the dependencies (although I don't see the point in it). Nevertheless, it now fails with a different error:

```
LAMBDA_WARNING: Unhandled exception. [...]
[ERROR] TypeError: Queue.__init__() got an unexpected keyword argument 'loop'
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 305, in vc_handler
    response = asgi_cycle(__vc_module.app, body)
  File "/var/task/vc__handler__python.py", line 202, in __call__
    self.app_queue = asyncio.Queue(loop=loop)
```

I could trace back to this line of `vc_init`:

https://github.com/vercel/vercel/blob/3101d2497f79fd39e927dd9527d0bee800445d28/packages/python/vc_init.py#L202

[According to the Python docs](https://docs.python.org/3/library/asyncio-queue.html#asyncio.Queue), the `loop` argument to the `Queue` was removed in Python 3.10

### PR DESCRIPTION
**Pull request by atlanswer**
Resolves: #11545

**Problem**:

ASGI application running with Vercel Python runtime 3.12 would crash with `500: INTERNAL_SERVER_ERROR
`and `Code: FUNCTION_INVOCATION_FAILED` because the `loop` parameter in `asyncio.Queue` was deprecated in 3.8 and then removed in 3.10, which was used in Mangum back in the day.

Vercel log
```
LAMBDA_WARNING: Unhandled exception. [...]
[ERROR] TypeError: Queue.__init__() got an unexpected keyword argument 'loop'
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 305, in vc_handler
    response = asgi_cycle(__vc_module.app, body)
  File "/var/task/vc__handler__python.py", line 202, in __call__
    self.app_queue = asyncio.Queue(loop=loop)
```

Code
https://github.com/vercel/vercel/blob/af29e9be49803be1f40664b57c4ea058bab43bae/packages/python/vc_init.py#L202

Ref
https://docs.python.org/3.8/library/asyncio-queue.html#:~:text=Deprecated%20since%20version%203.8%2C%20will%20be%20removed%20in%20version%203.10%3A%20The%20loop%20parameter.

**Fix**:

Since the oldest deployable Python runtime version on Vercel is 3.9, there's no reason to keep using the obsolete code. Porting the latest Mangum implementation should fix the issue.

Related PR: #11541

**Changes**:

- Using the new `HTTPCycle` ASGI runner from Mangum, replacing `ASGICycle`
- Add Mangum's LICENSE
- Replace logging with print for consistency

---

**Edited**:

Since #11675 has been merged, the maintainers can close this PR if you think this port is unnecessary.

### CODE REVIEW

**Comment by EndangeredMassa** [comment]
resolved in: https://github.com/vercel/vercel/pull/11675

Thanks for the PR!
