### ISSUE TITLE
[now-cli] Error when deploying now v1 project: Chalk template literal is missing 1 closing bracket (`}`)

### ISSUE THREAD

**Issue by pablogq** [vercel/vercel#3755]
After upgrading to `now@17.0.1` I'm getting the following error: `Error: Chalk template literal is missing 1 closing bracket (`}`)` during the deployment process.

Here is the complete console output:
```
Now CLI 17.0.1
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ WARN! You are using an old version of the Now Platform. More: https://zeit.co/guides/migrate-to-zeit-now │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> Deploying ~/tmp under #######
> Using project #######
> https://#######.now.sh [v1] [2s]
> Build completed
Error! An unexpected error occurred!
  Error: Chalk template literal is missing 1 closing bracket (`}`)
    at e.exports (/usr/local/lib/node_modules/now/dist/index.js:2:1500109)
    at chalkTag (/usr/local/lib/node_modules/now/dist/index.js:2:4107323)
    at Object.Chalk.t.template [as default] (/usr/local/lib/node_modules/now/dist/index.js:2:4105020)
    at /usr/local/lib/node_modules/now/dist/index.js:2:4024265
    at processTicksAndRejections (internal/process/task_queues.js:94:5) Error: Chalk template literal is missing 1 closing bracket (`}`)
    at e.exports (/usr/local/lib/node_modules/now/dist/index.js:2:1500109)
    at chalkTag (/usr/local/lib/node_modules/now/dist/index.js:2:4107323)
    at Object.Chalk.t.template [as default] (/usr/local/lib/node_modules/now/dist/index.js:2:4105020)
    at /usr/local/lib/node_modules/now/dist/index.js:2:4024265
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

Exited with code exit status 1
```

**Comment by rockymountainhigh1943** [comment]
Getting the same issue.

**Comment by drobnikj** [comment]
Same issue here. After updating to 17.0.1. 
Downgrading to 16.7.3, solve the issue.
`npm install -g now@16.7.3`

**Comment by styfle** [comment]
Thank you for reporting this issue!
It seems to be affecting v1 deployments and has been fixed in [7.0.3](https://github.com/zeit/now/releases/tag/now%4017.0.3).
