### ISSUE TITLE
Docker Support?

### ISSUE THREAD

**Issue by leo** [vercel/vercel#784]
_From @e-beach on July 22, 2017 21:7_

Are Docker based projects supported for now@beta? I get this error for a project which works using now@7.2.4.

```
elliott@elliott-pc ~/m/p/5609-Final-Project> ls
app/  Dockerfile*  README.md*  requirements.txt*  venv/

elliott@elliott-pc ~/m/p/5609-Final-Project> now
> Deploying "~/me/projects/5609-Final-Project" (aws) (us-west-1)
⠋ Building and bundling your app…> Error! An unexpected error occurred!
  Error: Cannot find module './static'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.get static [as static] (/home/elliott/me/projects/now/out/serverless/builders/index.js:6:12)
    at build (/home/elliott/me/projects/now/out/serverless/build.js:4:18)
    at deploy (/home/elliott/me/projects/now/out/providers/aws/deploy.js:101:25)
    at <anonymous> Error: Cannot find module './static'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.get static [as static] (/home/elliott/me/projects/now/out/serverless/builders/index.js:6:12)
    at build (/home/elliott/me/projects/now/out/serverless/build.js:4:18)
    at deploy (/home/elliott/me/projects/now/out/providers/aws/deploy.js:101:25)
    at <anonymous>
elliott@elliott-pc ~/m/p/5609-Final-Project> 

```

_Copied from original issue: zeit/now#39_

**Comment by leo** [comment]
The [latest beta release](https://github.com/zeit/now-cli/releases/tag/8.0.0-beta.10) supports Docker deployments. Feel free to give it a try!
